const bfsu = require("../sites/bfsu/bfsu");
const bjtu = require("../sites/bjtu/bjtu");
const bupt = require("../sites/bupt/bupt");
const byrio = require("../sites/byrio/byrio");
const cqu = require("../sites/cqu/cqu");
const cqupt = require("../sites/cqupt/cqupt");
const geekpie = require("../sites/geekpie/geekpie");
const ha = require("../sites/ha/ha");
const hit = require("../sites/hit/hit");
const hust = require("../sites/hust/hust");
const iscas = require("../sites/iscas/iscas");
const jcut = require("../sites/jcut/jcut");
const jlu = require("../sites/jlu/jlu");
const lzu = require("../sites/lzu/lzu");
const nano = require("../sites/tuna/nano");
const neo = require("../sites/tuna/neo");
const neu = require("../sites/neu/neu");
const neusoft = require("../sites/neusoft/neusoft");
const njtech = require("../sites/njtech/njtech");
const nju = require("../sites/nju/nju");
const njupt = require("../sites/njupt/njupt");
const nwafu = require("../sites/nwafu/nwafu");
const nyist = require("../sites/nyist/nyist");
const pku = require("../sites/pku/pku");
const qlut = require("../sites/qlut/qlut");
const sdu = require("../sites/sdu/sdu");
const siyuan = require("../sites/siyuan/siyuan");
const sustech = require("../sites/sustech/sustech");
const sysu = require("../sites/sysu/sysu");
const tuna = require("../sites/tuna/tuna");
const uestc = require("../sites/uestc/uestc");
const ustc = require("../sites/ustc/ustc");
const wsyu = require("../sites/wsyu/wsyu");
const xjtu = require("../sites/xjtu/xjtu");
const xtom = require("../sites/xtom/xtom");
const xtom_hk = require("../sites/xtom/xtom-hk");
const xtom_de = require("../sites/xtom/xtom-de");
const xtom_nl = require("../sites/xtom/xtom-nl");
const xtom_ee = require("../sites/xtom/xtom-ee");
const xtom_jp = require("../sites/xtom/xtom-jp");
const xtom_au = require("../sites/xtom/xtom-au");
const xtom_sg = require("../sites/xtom/xtom-sg");
const ynuosa = require("../sites/ynu/ynuosa");
const zhiyuan = require("../sites/zhiyuan/zhiyuan");
const zju = require("../sites/zju/zju");

const lint = require('./lint')

// Use static require inside each parser to get files from json-site.
module.exports = {
  "bfsu"    : async () => lint(await bfsu    ()),
  "bjtu"    : async () => lint(await bjtu    ()),
  "bupt"    : async () => lint(await bupt    ()),
  "byrio"   : async () => lint(await byrio   ()),
  "cqu"     : async () => lint(await cqu     ()),
  "cqupt"   : async () => lint(await cqupt   ()),
  "geekpie" : async () => lint(await geekpie ()),
  "ha"      : async () => lint(await ha      ()),
  "hit"     : async () => lint(await hit     ()),
  "hust"    : async () => lint(await hust    ()),
  "iscas"   : async () => lint(await iscas   ()),
  "jcut"    : async () => lint(await jcut    ()),
  "jlu"     : async () => lint(await jlu     ()),
  "lzu"     : async () => lint(await lzu     ()),
  "nano"    : async () => lint(await nano    ()),
  "neo"     : async () => lint(await neo     ()),
  "neu"     : async () => lint(await neu     ()),
  "neusoft" : async () => lint(await neusoft ()),
  "njtech"  : async () => lint(await njtech  ()),
  "nju"     : async () => lint(await nju     ()),
  "njupt"   : async () => lint(await njupt   ()),
  "nyist"   : async () => lint(await nyist   ()),
  "nwafu"   : async () => lint(await nwafu   ()),
  "pku"     : async () => lint(await pku     ()),
  "qlut"    : async () => lint(await qlut    ()),
  "sdu"     : async () => lint(await sdu     ()),
  "siyuan"  : async () => lint(await siyuan  ()),
  "sustech" : async () => lint(await sustech ()),
  "sysu"    : async () => lint(await sysu    ()),
  "tuna"    : async () => lint(await tuna    ()),
  "uestc"   : async () => lint(await uestc   ()),
  "ustc"    : async () => lint(await ustc    ()),
  "wsyu"    : async () => lint(await wsyu    ()),
  "xjtu"    : async () => lint(await xjtu    ()),
  "xtom"    : async () => lint(await xtom    ()),
  "xtom-hk" : async () => lint(await xtom_hk ()),
  "xtom-de" : async () => lint(await xtom_de ()),
  "xtom-nl" : async () => lint(await xtom_nl ()),
  "xtom-ee" : async () => lint(await xtom_ee ()),
  "xtom-jp" : async () => lint(await xtom_jp ()),
  "xtom-au" : async () => lint(await xtom_au ()),
  "xtom-sg" : async () => lint(await xtom_sg ()),
  "ynuosa"  : async () => lint(await ynuosa  ()),
  "zhiyuan" : async () => lint(await zhiyuan ()),
  "zju"     : async () => lint(await zju     ()),
};
