const nju = require("./nju");
const neusoft = require("./neusoft");
const tuna = require("./tuna");
const bfsu = require("./bfsu");
const nano = require("./nano");
const neo = require("./neo");
const hit = require("./hit");
const cqu = require("./cqu");
const xjtu = require("./xjtu");
const neu = require("./neu");
const pku = require("./pku");
const byrio = require("./byrio");
const cqupt = require("./cqupt");
const ynuosa = require("./ynuosa");
const xtom_hk = require("./xtom-hk");
const xtom = require("./xtom");
const xtom_de = require("./xtom-de");
const xtom_nl = require("./xtom-nl");
const xtom_ee = require("./xtom-ee");
const xtom_jp = require("./xtom-jp");
const xtom_au = require("./xtom-au");
const xtom_sg = require("./xtom-sg");
const njupt = require("./njupt");
const wsyu = require("./wsyu");
const bjtu = require("./bjtu");
const bupt = require("./bupt");
const njtech = require("./njtech");
const geekpie = require("./geekpie");
const qlut = require("./qlut");
const nyist = require("./nyist");
const jcut = require("./jcut");
const nwafu = require("./nwafu");
const hust = require("./hust");
const ha = require("./ha");

const lint = require('./lint')

// Use static require inside each parser to get files from json-site.
module.exports = {
  "nju"     : async () => lint(await nju     ()),
  "neusoft" : async () => lint(await neusoft ()),
  "tuna"    : async () => lint(await tuna    ()),
  "bfsu"    : async () => lint(await bfsu    ()),
  "nano"    : async () => lint(await nano    ()),
  "neo"     : async () => lint(await neo     ()),
  "hit"     : async () => lint(await hit     ()),
  "cqu"     : async () => lint(await cqu     ()),
  "xjtu"    : async () => lint(await xjtu    ()),
  "neu"     : async () => lint(await neu     ()),
  "pku"     : async () => lint(await pku     ()),
  "byrio"   : async () => lint(await byrio   ()),
  "cqupt"   : async () => lint(await cqupt   ()),
  "ynuosa"  : async () => lint(await ynuosa  ()),
  "xtom-hk" : async () => lint(await xtom_hk ()),
  "xtom"    : async () => lint(await xtom    ()),
  "xtom-de" : async () => lint(await xtom_de ()),
  "xtom-nl" : async () => lint(await xtom_nl ()),
  "xtom-ee" : async () => lint(await xtom_ee ()),
  "xtom-jp" : async () => lint(await xtom_jp ()),
  "xtom-au" : async () => lint(await xtom_au ()),
  "xtom-sg" : async () => lint(await xtom_sg ()),
  "njupt"   : async () => lint(await njupt   ()),
  "wsyu"    : async () => lint(await wsyu    ()),
  "bjtu"    : async () => lint(await bjtu    ()),
  "bupt"    : async () => lint(await bupt    ()),
  "njtech"  : async () => lint(await njtech  ()),
  "geekpie" : async () => lint(await geekpie ()),
  "qlut"    : async () => lint(await qlut    ()),
  "nyist"   : async () => lint(await nyist   ()),
  "jcut"    : async () => lint(await jcut    ()),
  "nwafu"   : async () => lint(await nwafu   ()),
  "hust"    : async () => lint(await hust    ()),
  "ha"      : async () => lint(await ha      ()),
};
